### ISSUE TITLE
Please add License

### ISSUE THREAD

**Issue by amanSin1** [ankitghosh00/Pacman_Game#1]
I recently came across your project and was really impressed by the work you've done. I'm considering using it in one of my own projects but noticed that there isn't a license file in the repository.

To ensure I'm using it correctly and to clarify how others can use or contribute to the project, would you mind adding a license? A popular open-source license like MIT, Apache 2.0, or GPL would be helpful, but feel free to choose whichever fits best for your project.

Thanks for sharing your work, and I look forward to your response!

**Comment by ankitghosh00** [comment]
Nice to meet you aman. Sorry for the late reply.  I was doing all these
works of my semester project in my college life.  You can use all these
projects as your own but one thing you have to do is to update whatever you
want, I have no problem.  But do one thing  everyone can use these projects
for free.  I've talked to many before, all using their personal for some
money.  Don't do that.  best wishes

**Comment by amanSin1** [comment]
Thanks for your response, and I really appreciate the permission to use and modify the project freely! I’ll make sure it stays accessible and non-commercial, as you requested.

To keep things clear for others who may also want to use or contribute to the project, would you be open to me adding a license file for you, like an MIT or CC BY-NC 4.0 license? Either of these would maintain your request for free usage without limiting contributions or adaptations.

Let me know what you think, and thanks again for the opportunity to work with your project!
